<?php

namespace App\Filament\Clusters\Post\Resources\PostCategories\Pages;

use App\Filament\Clusters\Post\Resources\PostCategories\PostCategoryResource;
use Filament\Actions\EditAction;
use Filament\Infolists\Components\TextEntry;
use Filament\Resources\Pages\ViewRecord;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Illuminate\Contracts\Support\Htmlable;

class ViewPostCategory extends ViewRecord
{
    protected static string $resource = PostCategoryResource::class;

    public function getSubheading(): string|Htmlable
    {
        return $this->record->name;
    }

    protected function getHeaderActions(): array
    {
        return [
            EditAction::make()
                ->modalWidth('md')
        ];
    }

    public function infolist(Schema $schema): Schema
    {
        parent::infolist($schema); // TODO: Change the autogenerated stub

        return $schema
            ->components([
                Section::make('Deskripsi')
                    ->columnSpanFull()
                    ->schema([
                        TextEntry::make('description')
                            ->hiddenLabel()
                    ])
            ]);
    }
}
