<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Achievement extends Model implements HasMedia
{
    use SoftDeletes, HasFactory, InteractsWithMedia;

    protected $fillable = [
        'slug',
        'institution_id',
        'name',
        'contestant',
        'description',
        'organizer',
        'year',
        'achievement_level',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'year' => 'integer',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Achievement $achievement) {
            $achievement->slug = Str::uuid()->toString();
        });
    }

    // TODO RELATIONSHIP
    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }
}
