<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Agenda extends Model
{
    use SoftDeletes, HasFactory;

    protected $fillable = [
        'slug',
        'name',
        'description',
        'start_date',
        'end_date',
        'location',
        'user_id',
        'validated_by',
        'institution_id',
        'status',
        'published_at',
        'is_active'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'start_date' => 'datetime',
            'end_date' => 'datetime',
            'published_at' => 'datetime',
            'is_active' => 'boolean'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Agenda $agenda) {
            $agenda->slug = Str::uuid()->toString();
        });
    }

    // TODO RELATIONSHIP
    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function validatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'validated_by');
    }

    // TODO SCOPES
    #[Scope]
    protected function filterByStatus(Builder $query, $status): Builder
    {
        return $query->where('status', $status);
    }

    #[Scope]
    protected function filterData(Builder $query, $request): Builder
    {
        $search = $request['search'] ?? null;

        $query->when($search, fn(Builder $query) => $query->whereLike('name', '%' . $search . '%'));

        return $query;
    }
}
