<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Announcement extends Model implements HasMedia
{
    use SoftDeletes, InteractsWithMedia, HasFactory;

    protected $fillable = [
        'slug',
        'name',
        'description',
        'user_id',
        'validated_by',
        'institution_id',
        'status',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Announcement $announcement) {
            $announcement->slug = Str::uuid()->toString();
        });
    }

    // TODO RELATIONSHIP
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function validatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'validated_by');
    }

    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }

    // TODO SCOPES
    #[Scope]
    protected function searchData(Builder $query, $search): Builder
    {
        if ($search) {
            $query->whereLike('name', '%' . $search . '%')
                ->orWhereHas('institution', fn($query) => $query->whereLike('name', '%' . $search . '%'));
        }

        return $query;
    }

    #[Scope]
    protected function filterByStatus(Builder $query, $status): Builder
    {
        return $query->where('status', $status);
    }
}
