<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class EducationalLevel extends Model
{
    protected $fillable = [
        'slug',
        'full_name',
        'short_name',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (EducationalLevel $educationalLevel) {
            $educationalLevel->slug = Str::uuid()->toString();
        });
    }

    // TODO RELATIONSHIP
    public function institutions(): HasMany
    {
        return $this->hasMany(Institution::class, 'educational_level_id');
    }
}
