<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class EducationalHistory extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'slug',
        'user_id',
        'educational_level_id',
        'institution_name',
        'major',
        'graduation_year',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'graduation_year' => 'integer',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (EducationalHistory $educationalHistory) {
            $educationalHistory->slug = Str::uuid()->toString();
        });
    }

    public function educationalLevel(): BelongsTo
    {
        return $this->belongsTo(EducationalLevel::class);
    }
}
