<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class EmployeePosition extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'slug',
        'user_id',
        'personnel_department_id',
        'institution_id',
        'school_year_id',
        'start_date',
        'end_date',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'start_date' => 'date',
            'end_date' => 'date',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (EmployeePosition $employeePosition) {
            $employeePosition->slug = Str::uuid()->toString();
        });
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    // TODO RELATHIONSHIP
    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }

    public function schoolYear(): BelongsTo
    {
        return $this->belongsTo(SchoolYear::class);
    }

    public function personnelDepartment(): BelongsTo
    {
        return $this->belongsTo(PersonnelDepartment::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    // TODO ATTRIBUTES
    protected function period(): Attribute
    {
        return Attribute::make(
            get: fn() => $this->start_date && $this->end_date ? Carbon::parse($this->start_date)->isoFormat('D MMM Y') . ' - ' . Carbon::parse($this->end_date)->isoFormat('D MMM Y') : null
        );
    }
}
