<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class Employee extends Model
{
    protected $fillable = [
        'slug',
        'user_id',
        'nip',
        'nuptk',
        'gender',
        'address',
        'religion',
        'place_of_birth',
        'date_of_birth',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'address' => 'array',
            'date_of_birth' => 'date',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Employee $employee) {
            $employee->slug = Str::uuid()->toString();
        });
    }

    // TODO RELATIONSHIP
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
