<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Extracurricular extends Model implements HasMedia
{
    use SoftDeletes, InteractsWithMedia, HasFactory;

    protected $fillable = [
        'slug',
        'name',
        'description',
        'institution_id',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Extracurricular $extracurricular) {
            $extracurricular->slug = Str::uuid()->toString();
        });
    }

    // TODO ATTRIBUTES
    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }

    // TODO SCOPES
    #[Scope]
    protected function institutionId(Builder $query, $institutionId): Builder
    {
        return $query->where('institution_id', $institutionId);
    }
}
