<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Extracurricular extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'slug',
        'name',
        'description',
        'institution_id',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Extracurricular $extracurricular) {
            $extracurricular->slug = Str::uuid()->toString();
        });
    }

    // TODO ATTRIBUTES
    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }
}
