<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Facility extends Model implements HasMedia
{
    use SoftDeletes, InteractsWithMedia;

    protected $fillable = [
        'slug',
        'name',
        'description',
        'institution_id',
        'construction_year',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'construction_year' => 'integer',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Facility $facility) {
            $facility->slug = Str::uuid()->toString();
        });
    }

    // TODO RELATIONSHIP
    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }
}
