<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Gallery extends Model implements HasMedia
{
    use SoftDeletes, InteractsWithMedia;

    protected $fillable = [
        'slug',
        'institution_id',
        'application_id',
        'name',
        'description',
        'type',
        'youtube_id',
        'action_url',
        'action_name'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Gallery $gallery) {
            $gallery->slug = Str::uuid()->toString();
        });
    }

    // TODO RELATIONSHIP
    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }

    // TODO SCOPES
    #[Scope]
    protected function filterByType(Builder $query, $type): Builder
    {
        return $query->where('type', $type);
    }

    // TODO ATTRIBUTES
    protected function thumbnail(): Attribute
    {
        return Attribute::make(
            get: fn() => $this->hasMedia('thumbnail') ? $this->getFirstMediaUrl('thumbnail') : null,
        );
    }
}
