<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Homebase extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'slug',
        'user_id',
        'institution_id',
        'appointment_date',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'appointment_date' => 'date',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Homebase $homebase) {
            $homebase->slug = Str::uuid()->toString();
        });

        static::saving(function (Homebase $homebase) {
            if ($homebase->is_active) {
                self::where('user_id', $homebase->user_id)
                    ->where('id', '!=', $homebase->id)
                    ->update(['is_active' => false]);
            }
        });
    }

    // TODO RELATIONSHIP
    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
