<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Navigation extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'slug',
        'serial_number',
        'category',
        'name',
        'post_id',
        'url',
        'open_new_tab',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'open_new_tab' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Navigation $navigation) {
            $navigation->slug = Str::uuid()->toString();
        });

        static::updated(function (Navigation $navigation) {
            if ($navigation->category) {
                SubNavigation::query()
                    ->where('navigation_id', $navigation->id)
                    ->delete();
            }
        });
    }

    public function post(): BelongsTo
    {
        return $this->belongsTo(Post::class);
    }

    public function subNavigations(): HasMany
    {
        return $this->hasMany(SubNavigation::class, 'navigation_id');
    }
}
