<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class NumberOfStudent extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'slug',
        'employee_position_id',
        'classroom_id',
        'rombel_id',
        'amount',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (NumberOfStudent $numberOfStudent) {
            $numberOfStudent->slug = Str::uuid()->toString();
        });
    }

    // TODO RELATIONSHIP
    public function classroom(): BelongsTo
    {
        return $this->belongsTo(Classroom::class);
    }

    public function employeePosition(): BelongsTo
    {
        return $this->belongsTo(EmployeePosition::class);
    }

    public function rombel(): BelongsTo
    {
        return $this->belongsTo(Rombel::class);
    }
}
