<?php

namespace App\Models;

use App\Enums\StatusData;
use App\Observers\PostObserver;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

#[ObservedBy([PostObserver::class])]
class Post extends Model implements HasMedia
{
    use SoftDeletes, HasSlug, InteractsWithMedia, HasFactory;

    protected $fillable = [
        'slug',
        'title',
        'type',
        'content',
        'post_category_id',
        'institution_id',
        'user_id',
        'reviewed_by',
        'status',
        'visibility',
        'password',
        'allow_comment',
        'tags',
        'unsplash_url'
    ];

    protected function casts(): array
    {
        return [
            'allow_comment' => 'boolean',
            'tags' => 'array'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Post $post) {
            $post->user_id = auth()->id();
        });

        static::saving(function (Post $post) {
            if ($post->status === StatusData::PUBLISHED->value && is_null($post->reviewed_by)) {
                $post->reviewed_by = auth()->id();
            }
        });
    }

    public function getSlugOptions(): SlugOptions
    {
        // TODO: Implement getSlugOptions() method.
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    // TODO RELATIONSHIP
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function reviewedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'reviewed_by');
    }

    public function postCategory(): BelongsTo
    {
        return $this->belongsTo(PostCategory::class);
    }

    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }

    // TODO SCOPES
    #[Scope]
    protected function filterData(Builder $query, $request): Builder
    {
        $search = $request['search'] ?? null;
        $postCategory = $request['post-category'] ?? null;
        $institution = $request['institution'] ?? null;
        $tag = $request['tag'] ?? null;

        if ($search) {
            $query->whereLike('title', "%$search%");
            $query->orWhereLike('content', "%$search%");
        }

        if ($postCategory) {
            $query->whereHas('postCategory', fn($query) => $query->where('slug', $postCategory));
        }

        if ($institution) {
            $query->whereHas('institution', fn($query) => $query->where('slug', $institution));
        }

        if ($tag) {
            $query->whereJsonContains('tags', $tag);
        }

        return $query;
    }

    #[Scope]
    protected function filterByStatus(Builder $query, $status): Builder
    {
        return $query->where('status', $status);
    }

    #[Scope]
    protected function filterByType(Builder $query, $type): Builder
    {
        return $query->where('type', $type);
    }

    // TODO ATTRIBUTES
    protected function thumbnail(): Attribute
    {
        return Attribute::make(
            get: fn() => $this->hasMedia('thumbanil') ? $this->getFirstMediaUrl('thumbnail') : ($this->unsplash_url ?? asset('assets/student-1.png')),
        );
    }
}
