<?php

namespace App\Models;

use App\Enums\StatusData;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Post extends Model implements HasMedia
{
    use SoftDeletes, HasSlug, InteractsWithMedia;

    protected $fillable = [
        'slug',
        'title',
        'type',
        'content',
        'post_category_id',
        'institution_id',
        'user_id',
        'reviewed_by',
        'status',
        'visibility',
        'password',
        'allow_comment',
        'tags'
    ];

    protected function casts(): array
    {
        return [
            'allow_comment' => 'boolean',
            'tags' => 'array'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Post $post) {
            $post->user_id = auth()->id();
        });

        static::saving(function (Post $post) {
            if ($post->status === StatusData::PUBLISHED->value && is_null($post->reviewed_by)) {
                $post->reviewed_by = auth()->id();
            }
        });
    }

    public function getSlugOptions(): SlugOptions
    {
        // TODO: Implement getSlugOptions() method.
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    // TODO RELATIONSHIP
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function reviewedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'reviewed_by');
    }

    public function postCategory(): BelongsTo
    {
        return $this->belongsTo(PostCategory::class);
    }

    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }
}
