<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class SchoolYear extends Model
{
    protected $fillable = [
        'slug',
        'first_year',
        'last_year',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'first_year' => 'integer',
            'last_year' => 'integer',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (SchoolYear $schoolYear) {
            $schoolYear->slug = Str::uuid()->toString();
        });

        static::saving(function (SchoolYear $schoolYear) {
            if ($schoolYear->is_active) {
                self::where('id', '!=', $schoolYear->id)
                    ->update(['is_active' => false]);
            }
        });
    }

    // TODO RELATIONSHIP
    public function employeePositions(): HasMany
    {
        return $this->hasMany(EmployeePosition::class, 'school_year_id');
    }

    // TODO ATTRIBUTES
    protected function year(): Attribute
    {
        return Attribute::make(
            get: fn() => $this->first_year . '/' . $this->last_year,
        );
    }
}
