<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class SubNavigation extends Model
{
    protected $fillable = [
        'slug',
        'serial_number',
        'navigation_id',
        'category',
        'name',
        'post_id',
        'url',
        'open_new_tab',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'open_new_tab' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (SubNavigation $subNavigation) {
            $subNavigation->slug = Str::uuid()->toString();
        });
    }
}
